### ISSUE TITLE
No longer works with new signatures

### ISSUE THREAD

**Issue by boostchicken** [opentracing-contrib/java-aws-sdk#9] opened 2019-06-07 00:07 UTC
message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: InvalidSignatureException; Request ID: JLE25C7RCQKSIOBUF0IQP29EU3VV4KQNSO5AEMVJF66Q9ASUAAJG)"

**Comment by malafeev** [comment] 2019-06-07 02:55
I reproduced this issue only in SpecialAgent, as you reported https://github.com/opentracing-contrib/java-specialagent/issues/86.
Did you try to use this library without SpecialAgent? Still failing?

**Comment by boostchicken** [comment] 2019-06-07 03:21
I have not, no desire to really.

**Comment by malafeev** [comment] 2019-06-07 03:24
ok, so I'm closing it now, because I found a problem in SpecialAgent.

**Closed by malafeev** 2019-06-07 03:24 UTC

**Comment by boostchicken** [comment] 2019-06-07 03:32
@malafeev care to share? I took a look and a few things jump out but I need to get this working sooner than later,

**Comment by malafeev** [comment] 2019-06-07 04:14
@boostchicken you need to disable apache-httpclient:
`-Dsa.instrumentation.plugin.apache-httpclient.enable=false`

**Comment by boostchicken** [comment] 2019-06-07 05:13
Yeah I just found that out a few minutes ago,  I finally looked at the apache code and its supeeeeeerrrr ugly.

Thanks man!
